sudo: required
dist: xenial
jdk:
  - openjdk11
script:
  - mvn clean package
  - mvn sonar:sonar
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"

deploy:
  provider: script
  script: "mvn heroku:deploy -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true"
  skip_cleanup: true
  on:
    branch: master